### ISSUE TITLE
Feature request: Clarify statement on blocking detection

### ISSUE THREAD

**Issue by kaerumy** [Sinar/blockedornot#2]
Clarify this better when blocking found.

"A well-known IP hosted by the government for blocked websites is returned by our ISP/Telco DNS."

"Instead of the intended IP address, this URL is being directed by TMNet DNS server to the IP address 175.139.142.25 for websites blocked by MCMC."

**Comment by Jeffrey04** [comment]
yea, will start working on the logging, and will include the proposed fix, would replacing `TMNet` to `ISP/Telco` work better?

**Comment by kaerumy** [comment]
I think TMNet (AS4788) is better because the backend for now is only testing on that network, and the results only reflect TMNet network and TMnet DNS.
